"""Export Firestore review_queue into a markdown review dashboard.

Firestore remains the source of truth. This script creates a readable projection
for operators and AI assistants.

Usage:
    python scripts/export_review_queue.py
    python scripts/export_review_queue.py --status all
    python scripts/export_review_queue.py --output docs/review/AI_REVIEW_QUEUE.md
    python scripts/export_review_queue.py --project capital-index-2026 --database "(default)"
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PROJECT_ID = "capital-index-2026"
DATABASE = "(default)"
DEFAULT_OUTPUT = Path("docs/review/AI_REVIEW_QUEUE.md")


@dataclass(frozen=True)
class ReviewItem:
    review_id: str
    status: str
    priority: str
    reason: str
    file_id: str
    doc_title: str
    sensitivity_class: str
    source: str
    source_collection: str
    source_decision_id: str
    trace_id: str
    created_at: str
    updated_at: str
    next_action: str
    char_count: int | None


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def review_item_from_dict(data: dict[str, Any], fallback_id: str) -> ReviewItem:
    return ReviewItem(
        review_id=str(data.get("review_id") or fallback_id),
        status=str(data.get("status") or "open"),
        priority=str(data.get("priority") or "normal"),
        reason=str(data.get("reason") or "review_required"),
        file_id=str(data.get("file_id") or ""),
        doc_title=str(data.get("doc_title") or ""),
        sensitivity_class=str(data.get("sensitivity_class") or ""),
        source=str(data.get("source") or ""),
        source_collection=str(data.get("source_collection") or ""),
        source_decision_id=str(data.get("source_decision_id") or ""),
        trace_id=str(data.get("trace_id") or ""),
        created_at=str(data.get("created_at") or ""),
        updated_at=str(data.get("updated_at") or ""),
        next_action=str(data.get("next_action") or ""),
        char_count=_int_or_none(data.get("char_count")),
    )


def _int_or_none(value: Any) -> int | None:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def sort_items(items: list[ReviewItem]) -> list[ReviewItem]:
    priority_rank = {"urgent": 0, "high": 1, "normal": 2, "low": 3}
    return sorted(
        items,
        key=lambda item: (
            priority_rank.get(item.priority, 9),
            item.created_at or item.updated_at,
            item.review_id,
        ),
    )


def render_markdown(items: list[ReviewItem], *, generated_at: str, status_filter: str) -> str:
    sorted_items = sort_items(items)
    open_count = sum(1 for item in sorted_items if item.status == "open")
    lines = [
        "# AI Review Queue",
        "",
        "<!-- Generated by scripts/export_review_queue.py. Firestore is source of truth. -->",
        "",
        f"Generated: `{generated_at}`",
        f"Status filter: `{status_filter}`",
        f"Items: `{len(sorted_items)}`",
        f"Open: `{open_count}`",
        "",
    ]

    if not sorted_items:
        lines.extend(["No review items found.", ""])
        return "\n".join(lines)

    lines.extend(
        [
            "| Priority | Status | Reason | Title | File | Updated |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for item in sorted_items:
        lines.append(
            "| "
            + " | ".join(
                [
                    _cell(item.priority),
                    _cell(item.status),
                    _cell(item.reason),
                    _cell(item.doc_title or "(untitled)"),
                    _cell(item.file_id),
                    _cell(item.updated_at or item.created_at),
                ]
            )
            + " |"
        )

    lines.append("")
    for item in sorted_items:
        lines.extend(
            [
                f"## {item.review_id}",
                "",
                f"- Status: `{item.status}`",
                f"- Priority: `{item.priority}`",
                f"- Reason: `{item.reason}`",
                f"- File ID: `{item.file_id}`",
                f"- Title: `{item.doc_title or '(untitled)'}`",
                f"- Sensitivity: `{item.sensitivity_class}`",
                f"- Source: `{item.source}` / `{item.source_collection}`",
                f"- Source decision: `{item.source_decision_id}`",
                f"- Trace: `{item.trace_id}`",
                f"- Next action: `{item.next_action}`",
                f"- Char count: `{'' if item.char_count is None else item.char_count}`",
                f"- Created: `{item.created_at}`",
                f"- Updated: `{item.updated_at}`",
                "",
            ]
        )

    return "\n".join(lines)


def _cell(value: str) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def load_review_items(
    status_filter: str,
    limit: int | None,
    *,
    project_id: str = PROJECT_ID,
    database: str = DATABASE,
) -> list[ReviewItem]:
    from google.cloud import firestore

    db = firestore.Client(project=project_id, database=database)
    docs = db.collection("review_queue").stream()
    items: list[ReviewItem] = []
    for doc in docs:
        item = review_item_from_dict(doc.to_dict() or {}, doc.id)
        if status_filter != "all" and item.status != status_filter:
            continue
        items.append(item)

    sorted_items = sort_items(items)
    return sorted_items[:limit] if limit else sorted_items


def write_dashboard(path: Path, markdown: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(markdown.rstrip() + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Export Firestore review_queue to markdown.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--project", default=PROJECT_ID)
    parser.add_argument("--database", default=DATABASE)
    parser.add_argument("--status", default="open", choices=["open", "closed", "all"])
    parser.add_argument("--limit", type=int, default=100)
    args = parser.parse_args()

    items = load_review_items(args.status, args.limit, project_id=args.project, database=args.database)
    markdown = render_markdown(items, generated_at=utc_now(), status_filter=args.status)
    write_dashboard(args.output, markdown)
    print(f"Wrote {args.output} ({len(items)} items)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
